### ISSUE TITLE
Alternative Way Of Disabling?

### ISSUE THREAD

**Issue by jgoodhouse-nr** [bluesliverx/disable-github-multibranch-status-plugin#2]
Thanks for the plugin! I'm curious if there is an alternative way of disabling status notifications, e.g., from within a Jenkinsfile instead? I'm struggling to find how this could be done.

**Comment by bluesliverx** [comment]
Unfortunately, there isn't a way to do this from a Jenkinsfile.  The problem is that by the time the Jenkinsfile executes, the status notification has already been sent to GitHub.  It needs to be disabled in the job configuration itself.  I use this plugin to disable all notifications, and then use custom code to call github as needed (I think the github plugin can do this as well) with my own status notifications.
